### ISSUE TITLE
panel highlight missing in various themes

### ISSUE THREAD

**Issue by brownsr** [linuxmint/cinnamon-spices-themes#111]
The piece of CSS that turns on a highlight on the panel is missing in some themes.  This means that in the panel settings the colour highlight that shows which panel the user is currently on is missing.

I've corrected this in themes where we do not believe there is any active maintainer, but for those themes in active maintenance please let me know if you would like me to raise a PR against these themes for you to check and approve.  

As this missing highlight causes a piece of functionality in the Cinnamon settings not to appear to work, it seems appropriate for me to treat this as a bug, so I will plan to make the change in a few days if I have not heard back from theme maintainers.  I hope that seems reasonable to all. 

Additional comments below are for specific themes that this may apply to.

**Comment by brownsr** [comment]
@fmcgorenc I've noticed that I missed this when I uploaded your themes.  Are you happy that I update this in your various themes (Mint XP, Mint OC, Modern Mint etc.)

**Comment by brownsr** [comment]
@Elbullazul Your theme ChromeOS has this issue.  The change required is very minor, most themes just need 
#panel:highlight {
    background-color: #aa5555;
}

**Comment by brownsr** [comment]
@Brahim Your themes Vivaldi and Vivaldi-ZorinOS have this issue

**Comment by brownsr** [comment]
@edoz90 Your theme Numix-Cinnamon-transparent has this issue.

**Comment by brownsr** [comment]
@vlad1777d Just spotted your github page.  Glad to find you are still active.  Your various Glass* themes in the mint repository have this issue.

**Comment by vlad1777d** [comment]
@brownsr , thank you, I just corrected this. But I'll upload it when I'll finish my script, which makes Mint theme from Mint Classic, because doing it manually was hell =)

I'll try to make it as soon as possible and will try to not forget write here about result.

**Comment by Elbullazul** [comment]
@brownsr thanks for the tip, I'll fix this

**Comment by Elbullazul** [comment]
@brownsr just wondering what this piece of code does.

**Comment by brownsr** [comment]
![screenshot from 2017-03-23 21-40-58](https://cloud.githubusercontent.com/assets/6322481/24271553/819c98a8-1011-11e7-861b-97a703dddd29.png)

**Comment by vlad1777d** [comment]
@brownsr , I reworked all: https://github.com/vlad1777d/Cinnamon_Glass_Themes
Do themes now have other structure?
_(I had noticed 'files' folder in [cinnamon-spices-themes](https://github.com/linuxmint/cinnamon-spices-themes) repository and moved info to info.json commit)_

**Comment by brownsr** [comment]
The file structure is described here  https://github.com/linuxmint/cinnamon-spices-themes/blob/master/README.md  The loadable theme details have not changed, but they are put under a 'files' directory, and the authorship is in info.json.  The link describes everything relevant.  If you have reworked them all from a master using a script, then could you point me towards which is the best one to check out ?  It would seem sensible if I gave it a quick lookover before we work out how to merge so if there are any issues you only have to fix in one place.

**Comment by brownsr** [comment]
Hi @vlad1777d I downloaded your mint classic and gave it a go, as I re-read your comments and thought that seemed to be your base to build your themes.  I spotted two things, the first is that the highlights around the icons burst out of a vertical panel, and the icons are offset.  You already have CSS for applet-box.vertical, so just set padding-left and padding-right to 0 to fix that. The second is something I've been picking up in a few places, where if you have multiple keyboards and flags turned on, and the keyboard applet showing, then the keyboard flag displays with excessive space around it in a vertical panel.  That's pretty minor admittedly, playing around with the height in panel-status-button seems to fix that. If you look at recent commits you'll see some recent changes to address this in various themes, all quite experimental I will admit.

**Comment by vlad1777d** [comment]
@brownsr , thank you. Yes, I based on my themes, because they are more recent version, than in [cinnamon-spices-themes](https://github.com/linuxmint/cinnamon-spices-themes).
I'll read all info, that you provided, than will correct my themes and scripts, according to all new commits in that repository. I just reworked some shadows, border-radiuses, again updated themes; some time later I'll add several additional color variations (they all are generated from "Mint" or "Mint Classic" automatically).

Also in my theme I placed special marks on that classes, which function I don't know; can I ask about them somewhere?

**Comment by brownsr** [comment]
Ask away, I'll do my best, though there will be some things that I have to research.  The default theme could do with some more explanatory comments anyway.

**Comment by brownsr** [comment]
@vlad1777d  Not sure just where we are.  Are you going to apply the corrections I suggested above, and I then pull new cuts of your themes from your repositories ?  Or do you want me to pull new cuts of your repositories and replace what we have in this cinnamon-spices-themes repository, and then for me to separately apply the corrections ?  Or are you planning to submit PRs ?  All are possible, I'm just not sure what you are expecting.

**Comment by brownsr** [comment]
@vlad1777d Hi Vladislav.  I've applied the latest versions in your repository.  I set the l/r padding to 0 in applet-box.vertical as mentioned above. Thanks for your new versions :)

**Comment by brownsr** [comment]
All known panel highlight issues now corrected

**Comment by vlad1777d** [comment]
@brownsr , sorry, I had not time to correct my themes according new changes in file locations.
I'll do it and I'll look through all your changes in them.

**Comment by vlad1777d** [comment]
@brownsr ,
In my themes I specially marked some classes, that I could not figure out what they stand for.
Some of them I had added from Mint-X theme after it's updates.
Classes:

- .popup-inactive-menu-item
- .notification-button (where is it? neither on panel, nor in menu I hadn't seen it)
-

**Comment by JosephMcc** [comment]
I can give you a few of these off the top of my head

> .popup-inactive-menu-item

This is used for some applet menu items to show a menu item is unselectable. I think you can see it in the menu for the power applet

> .notification-button (where is it? neither on panel, nor in menu I hadn't seen it)

These are (surprise) for buttons in notifications. Some things like media players show buttons in notifications. I think both banshee and rhythmbox do this :)

> .osd-window

This is the little window that pops up when you use your keyboard function keys to do things like change the volume or screen brightness

> .tile-preview.snap
.tile-hud.snap

If you move your window near an edge to pull up the tile hud or preview a little dialog pops up and says hole <Ctrl> to enter snap mode. Try it. This is theming for when you do that

>  .cinnamon-mount-operation-icon
    .mount-password-reask
    .show-processes-dialog
    .mount-question-dialog

These are junk and unused now, feel free to remove them.

**Comment by vlad1777d** [comment]
@JosephMcc , thank you )

**Comment by vlad1777d** [comment]
@brownsr , seems, that your change to to .applet-box.vertical:
`My:  {'padding-left': '5px', 'padding-right': '5px'}`
`Your:  {'padding-left': '0px', 'padding-right': '0px'}`
just enlarges language flag.
I'll try to merge my cinnamon.css with all your earlier commits, just will find them =)

**Comment by vlad1777d** [comment]
@brownsr , tell me please, for what did you added that two lines (marked with "+") ?
I can't figure it out. They were added to `Glass-Mint/files/Glass Mint/cinnamon/cinnamon.css`

> .popup-separator-menu-item {
 /* ('RU') Разделитель (линия). */
 	background: rgba(0,0,0,0.1);
 	border: 1px solid rgba(220,220,220,0.1);
 	border-top: 0px;
 	border-left: 0px;
 	border-right: 0px;
>\+	-gradient-start: rgba(51,51,51,1);
>\+	-gradient-end: #555555;
 	color: #444;
 	box-shadow: inset 0px 1px 2px rgba(0,0,0,0.2);
 	height: 0.1em;
 	/*min-width: 12px;*/ /* ('RU') убрал чтобы апплеты не уменьшались в размерах в случае,
 	если список окон увеличится и не останется места на панели */
 }

Commit: 5a70a73061c1c2139a39d97db5389a7e4f374833

I'll add them, if they're needed.

**Comment by Odyseus** [comment]
Hello, everybody.

@vlad1777d: Those two plus signs aren't part of the file/commit. Those plus signs are part of the *GitHub highlighting* and informs you that those two lines were added. Click the button labelled **View** to see the whole file without the *diff overlay* (See image).

![screenshot from 2017-05-25 00-36-41](https://cloud.githubusercontent.com/assets/3822556/26434975/446e490c-40e2-11e7-9c9a-bdcc16221481.png)

**Comment by vlad1777d** [comment]
@Odyseus , yes, thanks, I know it. I don't understand that changes: they do nothing: add nothing, change nothing.

**Comment by vlad1777d** [comment]
@brownsr , about icon in keyboard applet:
- changing `icon-size` in `.applet-icon` doesn't change icon's size (just can enlarge applet's size)
- adding padding to `.applet-icon` makes icon lesser, but it would be lesser and in horizontal panel, I couldn't figure out, how to make it only to case with vertical panel
- adding to `.applet-box.vertical`: `padding-left` and `padding-right` changed size of that icon. But on panel launchers applet now is padding to 5 px. I left it so. Because it's the most normal variant: that panel launchers applet looks normal, it's enough large to easy pressing on it.

- that extra space below seems to be item with some class, which I can't find in .css files.

**Comment by Odyseus** [comment]
Hello, everybody.

@vlad1777d: Very sorry for my dumb response. I completely misread your question.

> I don't understand that changes: they do nothing: add nothing, change nothing.

You must be looking at the wrong place. The **popup-separator-menu-item** class changes the separators that are inside menu popups. See image.

![example](https://cloud.githubusercontent.com/assets/3822556/26438222/0c2ed474-40f8-11e7-8b08-5569da54620a.png)

That red line is styled by the **-gradient-start** and **-gradient-end** properties.

Are you actually reloading the modified theme correctly? I would suggest you to simply restart Cinnamon, it will do a *more clean* reload of the theme.

**Comment by JosephMcc** [comment]
> I would suggest you to simply restart Cinnamon, it will do a more clean reload of the theme.

Alt+F2 then rt is the easiest way to reload the theme when making tweaks.

**Comment by vlad1777d** [comment]
@Odyseus , @JosephMcc , thanks, I know how to reload it (when only .css changed it's enough to reload theme itself: in cinnamon-control-center to press on theme button and choose current theme (which is active not), it'll be reloaded). If I changed .svg\.png files - than I need only to reload Cinnamon.

@Odyseus , strange, that I had not such result. I'll try to do it another time.

**Comment by Odyseus** [comment]
@vlad1777d.

Just an observation (probably another dumb response from my part. LOL). If you are using the code exactly as you posted it on you message, then you will never see the result, because the entire block is commented out and is invalid CSS.

This is how you posted it:
```css
.popup-separator-menu-item {
/* ('RU') Разделитель (линия). /
background: rgba(0,0,0,0.1);
border: 1px solid rgba(220,220,220,0.1);
border-top: 0px;
border-left: 0px;
border-right: 0px;
+ -gradient-start: rgba(51,51,51,1);
+ -gradient-end: #555555;
color: #444;
box-shadow: inset 0px 1px 2px rgba(0,0,0,0.2);
height: 0.1em;
/min-width: 12px;/ / ('RU') убрал чтобы апплеты не уменьшались в размерах в случае,
если список окон увеличится и не останется места на панели */
}
```

And this is how it actually should look like to actually work.
```css
.popup-separator-menu-item {
/* ('RU') Разделитель (линия). */
background: rgba(0,0,0,0.1);
border: 1px solid rgba(220,220,220,0.1);
border-top: 0px;
border-left: 0px;
border-right: 0px;
-gradient-start: rgba(51,51,51,1);
-gradient-end: #555555;
color: #444;
box-shadow: inset 0px 1px 2px rgba(0,0,0,0.2);
height: 0.1em;
/* min-width: 12px; ('RU') убрал чтобы апплеты не уменьшались в размерах в случае,
если список окон увеличится и не останется места на панели */
}
```

**Comment by vlad1777d** [comment]
@Odyseus , thank you very much, I know it =) I specially write there pluses for @brownsr to pay attention on them. Your responses are not dumb, what would be if I didn't knew this and nobody told be this ?
I use Cinnamon from it's first version and made my themes near version 1.4 (if I remember it right), remember when I adapted it for 1.6 or 1.8 and then I didn't knew anything about css, and sometimes people helped me, so I know this =)

Strange, that your code work, mine don't work:
![2017-05-26 10-09-20](https://cloud.githubusercontent.com/assets/12682937/26484797/ca08b47e-41fc-11e7-98cc-67b413dbc414.png)
(I restarted Cinnamon and three times spat through the left shoulder =) But it didn't helped me)
Can you send me full class text, which painted your separator to red ?

**Comment by Odyseus** [comment]
Hello, @vlad1777d.

> Can you send me full class text, which painted your separator to red ?

Of course. I use a theme based on the Mint-X family of themes.

```css
.popup-separator-menu-item {
    -gradient-height: 1px;
    -gradient-start: rgb(210, 210, 210);
    -gradient-end: rgb(210, 210, 210);
    -margin-horizontal: 0;
    height: 1px;
}
```

See the property called **-gradient-height**? If I remove it or comment it out, then I get the same result as you. The separator is not visible. This is due to the fact that some CSS properties in the Cinnamon themes *"are kind of mandatory"*.

Maybe you are better off starting from scratch your theme based on the default Cinnamon theme (/usr/share/cinnamon/theme) and not working over your old version of your theme. You will find several occurrences of these *"mandatory CSS properties"* that can give you a headache. If you base your theme in the default Cinnamon theme, then those *"mandatory CSS properties"* are already there.

**Comment by vlad1777d** [comment]
@Odyseus , yes, I had not it. So I asked, for what are that lines needed =)

About basing on standard theme, it's not best. In standard theme there are classes, that are not used in CInnamon
_(you can see my [question higher](https://github.com/linuxmint/cinnamon-spices-themes/issues/111#issuecomment-303018038), last group of properties is present in that theme and is not used)_.

Also, I think, in my theme all is better structured and has understood comments under each class\property, please, look [here](https://github.com/vlad1777d/Cinnamon_Glass_Themes/blob/master/Glass-Mint/files/Glass-Mint/cinnamon/cinnamon.css). That comments appeared after hours of testing =)

Also I have script [here](https://github.com/vlad1777d/Cinnamon_Glass_Themes/blob/master/variation%20scripts/make_mint_from_classic.py), which has "compare" and "auto-compare" functions. It can parse .css files and tell me, which new classes were added to standard theme (and which new properties).
_(but I need to copy that .css file to Glass-Mint or Glass-Mint-Classic folder)_

**Comment by Odyseus** [comment]
@vlad1777d

> So I asked, for what are that lines needed

I will explain it to you the best I can, although, it may not be technically correct. In the case of the **popup-separator-menu-item** class, those properties (*-gradient-...*) are used to programmatically create the separator elements (See the lines on [Cinnamon's code](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L507-L510) were they are used.).
