### ISSUE TITLE
Windows-10: Scaling problem using hidpi

### ISSUE THREAD

**Issue by michel-m** [linuxmint/cinnamon-spices-themes#114]
Hello,

First of all, I would like to thank you for the great work.
Now, I'm having what I believe to be a scaling issue with Windows 10 theme, on a high dpi display.

As a picture is worth a thousand words, here are a few screenshots of the same panels using first Windows 10 theme's controls, and then Adwaita's:

![screenshot from 2017-03-13 17-18-20](https://cloud.githubusercontent.com/assets/2655039/23864116/db6ad5c8-0811-11e7-805a-5ceb591f1538.png)
![screenshot from 2017-03-13 17-19-01](https://cloud.githubusercontent.com/assets/2655039/23864121/e051196c-0811-11e7-9335-0970e3b36b8e.png)
![screenshot from 2017-03-13 17-17-59](https://cloud.githubusercontent.com/assets/2655039/23864134/e8bbc5b6-0811-11e7-998d-01d6d940183a.png)
![screenshot from 2017-03-13 17-19-15](https://cloud.githubusercontent.com/assets/2655039/23864142/ec863fbe-0811-11e7-89e0-317b2353060c.png)
![screenshot from 2017-03-13 17-18-37](https://cloud.githubusercontent.com/assets/2655039/23864146/f0a7473c-0811-11e7-9f3d-4e473526023a.png)
![screenshot from 2017-03-13 17-18-51](https://cloud.githubusercontent.com/assets/2655039/23864154/f3889f64-0811-11e7-8389-3eca6178ba91.png)

Although I'm using Cinnamon 3.2.8 and I know it's not fully supported by the theme yet, it works without any noticeable problem on my other computer, which uses the same version of Cinnamon, but on a 1920x1080 resolution display.

I don't know what log file content would be useful to you guys, so let me know if you need anything else to diagnostic the issue.

**Comment by JosephMcc** [comment]
Please add the name of the theme in the issue title.

**Comment by JosephMcc** [comment]
Taking a quick look, the theme seems to be missing some assets for proper HiDPI support. If you look here: https://github.com/linuxmint/mint-themes-gtk3/blob/master/usr/share/themes/Mint-X/gtk-3.0/gtk-widgets-assets.css#L8 you'll notice assets like checkboxes are provided in two sizes. One for normal display and one for HiDPI. This theme is missing the double scaled versions.

**Comment by Elbullazul** [comment]
@JosephMcc will fix it, just had 0 idea what those 'scaled' assets were for.

@michel-m sorry for this inconvenience, will post as soon as the bug is fixed

**Comment by JosephMcc** [comment]
@Elbullazul I think supported for that was added in 3.10 and the theme will probably no longer work in any earlier versions once you added. I think currently you require gtk3.6 or something but I doubt much uses that anymore.

**Comment by brownsr** [comment]
@michel-m The theme author @Elbullazul has pushed some changes through, which I have just pulled into production.  I can't easily check hi-dpi on my modest laptop, so if you have the chance to check this and confirm if the problem is solved then that would be appreciated.

**Comment by michel-m** [comment]
@brownsr, I'll be able to give you my feedback on Monday.
Many thanks to you and @Elbullazul !

**Comment by michel-m** [comment]
It works perfectly, thank you very much!
