### ISSUE TITLE
Photocopy: background-problem with Weather Desklet

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-spices-themes#115]
Install Weather Desklet, place it onto the desktop and choose Photocopy as desktop theme -> you got a menu-like background behind, above and below the Weather Desklet (tried to paste a screenshot here, but that doesn't work).

**Comment by brownsr** [comment]
Corrected, works OK for the desklets I had to hand.

**Comment by Mintulix** [comment]
Thanks, looks better now, but there's still a glitch: I use 0% opacity with the Weather Desklet, but it looks like 100% black (only with Photocopy, all other themes look correct).

**Comment by brownsr** [comment]
will take a look at that when I can.

**Comment by brownsr** [comment]
Pushed a change earlier on today.  Hope that works for you.

**Comment by Mintulix** [comment]
Thanks to your code changes I knew where to look at. I changed one more thing for me to get 0% opacity:
`.desklet {
    color: #fff;
/*    background-color: rgba(80, 80, 80, 0.8);*/
    border-radius: 4px;
}
`
But you can leave it like it is, of course. Greetings
