### ISSUE TITLE
white carracters

### ISSUE THREAD

**Issue by Polohpi** [linuxmint/cinnamon-spices-themes#143]
Hello,

In the kiss kool viper theme, when i want to write some texte in the search bar of youtube (for exemple), the color of the text is white so i can't see what's going on. This problem stops when i change the theme of linux. 

thanks

(i'm using mozilla for web browser)

**Comment by Elbullazul** [comment]
@Polohpi it's a problem with firefox itself, it loads *certain* properties from GTK and others from the webpage. that's why tou get white text.

unfortunately, it seems this issue will be there until firefox updates their rendering method, which can be long enough

you can always change the text color to something with a bit more contrast (ex. f1f1f1)

**Comment by Polohpi** [comment]
true. In wich file and in which line i can do that ? :)
thanks

**Comment by Elbullazul** [comment]
in ```css
.entry {
  border: 1px solid;
  padding: 5px 8px;
  border-radius: 3px;
  transition: all 200ms cubic-bezier(0.25, 0.46, 0.45, 0.94);
  color: #FFFFFF;
  border-color: #292929;
  background-image: url("Sans titre1.png");
  background-image: linear-gradient(to bottom, #404040); }
  .entry.image.left {
    padding-left: 0; }
  .entry.image.right {
    padding-right: 0; }
  .entry.flat, .entry.flat:focus {
    padding: 2px;
    color: #FFFFFF;
    border-color: #292929;
    background-image: url("Sans titre1.png");
    background-image: linear-gradient(to bottom, #404040);
    border: none;
    border-radius: 0; }
  .entry:focus {
    background-clip: border-box;
    color: #FFFFFF;
    border-color: #292929;
    background-image: url("Sans titre1.png");
    background-image: linear-gradient(to bottom, #404040);
    box-shadow: inset 1px 0 #e72c2c, inset -1px 0 #e72c2c, inset 0 1px #e72c2c, inset 0 -1px #e72c2c; }
  .entry:insensitive {
    color: rgba(218, 218, 218, 0.55);
    border-color: rgba(41, 41, 41, 0.55);
    background-color: rgba(64, 64, 64, 0.55);
    background-image: linear-gradient(to bottom, rgba(64, 64, 64, 0.55)); }
  .entry:selected, .entry:selected:focus {
    background-color: #e72c2c;
    color: #ffffff; }
  .entry.progressbar {
    margin: 2px 12px;
    border-radius: 0;
    border-width: 0 0 2px;
    border-color: #e72c2c;
    border-style: solid;
    background-image: none;
    background-color: transparent;
    box-shadow: none; }
  .entry.warning {
    color: #ffffff;
    border-color: #292929;
    background-image: linear-gradient(to bottom, #ab6239); }
    .entry.warning:focus {
      color: #ffffff;
      background-image: linear-gradient(to bottom, #F27835);
      box-shadow: none; }
    .entry.warning:selected, .entry.warning:selected:focus {
      background-color: #ffffff;
      color: #F27835; }
  .entry.error {
    color: #ffffff;
    border-color: #292929;
    background-image: linear-gradient(to bottom, #b1413b); }
    .entry.error:focus {
      color: #ffffff;
      background-image: linear-gradient(to bottom, #FC4138);
      box-shadow: none; }
    .entry.error:selected, .entry.error:selected:focus {
      background-color: #ffffff;
      color: #FC4138; }
  .entry.image {
    color: #bbbbbb; }
  .osd .entry {
    color: #FFFFFF;
    border-color: rgba(22, 22, 22, 0.4);
    background-image: linear-gradient(to bottom, rgba(109, 109, 109, 0.4));
    background-color: transparent; }
    .osd .entry.image, .osd .entry.image:hover {
      color: inherit; }
    .osd .entry:focus {
      color: #ffffff;
      border-color: rgba(22, 22, 22, 0.4);
      background-image: linear-gradient(to bottom, #e72c2c); }
    .osd .entry:insensitive {
      color: rgba(195, 195, 195, 0.55);
      background-image: linear-gradient(to bottom, rgba(109, 109, 109, 0.25)); }
```

change
```css
color: #FFFFFF;```

to ```css
color: #F1F1F1;
```

**Comment by Polohpi** [comment]
Thanks for the answer. I have to change all the lines with color: #FFFFFF; ?

**Comment by Elbullazul** [comment]
@Polohpi only in the entry class and subclasses

**Comment by Polohpi** [comment]
Thanks ! :)
