### ISSUE TITLE
Dashed borders around every control in Linux Mint 17.3

### ISSUE THREAD

**Issue by sporifolous** [linuxmint/cinnamon-spices-themes#151]
I'm getting a grey dashed border around every box/control in the interface when using the Controls.

**Comment by JosephMcc** [comment]
The bug report doesn't do any good without knowing what theme you are talking about. In many cases those are "focus" indicators and the theme is using them intentionally.

**Comment by sporifolous** [comment]
Sorry, this was meant for the Mint-Y-Yltra-Dark theme. And the borders I don't think are focus indicators, unless every control in every window simultaneously have focus. 
![image](https://cloud.githubusercontent.com/assets/2438527/25505327/e245c8a8-2b66-11e7-8ecf-2911f7c3f171.png)

**Comment by JosephMcc** [comment]
The problem is the gtk version in Mint17.3. The Mint-Y theme was designed for gtk3.18/Mint18.
