### ISSUE TITLE
Error Message with Available themes (online)

### ISSUE THREAD

**Issue by callagg2** [linuxmint/cinnamon-spices-themes#157]
~ $ inxi -F
System:    Host: Aspire-R3700 Kernel: 4.4.0-53-generic x86_64 (64 bit)
           Desktop: Cinnamon 3.4.0  Distro: Linux Mint 18.1 Serena

On start menu
Select "LM Menu" -> "Preferences" ->Themes" -> "Add/Remove Desktop Themes" -> "Available themes (online)" 
I get 
"Something went wrong with the spices download.  Please try refreshing the list again.
Details:  No JSON object could be decoded"

But after I click refresh it seems to work fine - so maybe we need a disclaimer in case people think it is not there.

**Comment by brownsr** [comment]
This area has been reworked substantially for Cinnamon 3.6, so I am closing this issue as it works in quite a different way now.  Do please retest when you are on Cinnamon 3.6 and raise a new issue if you find any similar problems.

Regards

Simon
