### ISSUE TITLE
Mint-Y-Dark-Blue: Still Some Colors To Change From Mint-Y?

### ISSUE THREAD

**Issue by professorNim** [linuxmint/cinnamon-spices-themes#212]
Specifically, there are some greens for workspaces, the calendar, and the window list [here](https://github.com/linuxmint/cinnamon-spices-themes/tree/master/Mint-Y-Dark-Blue/files/Mint-Y-Dark-Blue/cinnamon/misc) and [here](https://github.com/linuxmint/cinnamon-spices-themes/tree/master/Mint-Y-Dark-Blue/files/Mint-Y-Dark-Blue/cinnamon/panel).

I'm also seeing a red gradient when scrolling to the bottom of lists, rather that what I had expected (blue). Is this coloring controlled by the overshoot.* css rules [here](https://github.com/linuxmint/cinnamon-spices-themes/blob/master/Mint-Y-Dark-Blue/files/Mint-Y-Dark-Blue/gtk-3.0/gtk.css#L2480)? If so, was this red coloring chosen on purpose? It doesn't seem to mesh with the rest of the theme.

There could be other areas too, but I have no idea what each css rule styles, this is my first time looking at a theme...

**Comment by brownsr** [comment]
There doesn't seem to be a current author for this theme.  If you want to send updates to fix these things you have noticed through as a PR then I will review them and merge them if they are OK.  There are some simple git instructions in the readme for this repository if that would be helpful.

Regards

Simon
