### ISSUE TITLE
Check Authors of Themes

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/cinnamon-spices-themes#221]
Since the cinnamon themes have been ported to GitHub, it it still unclear for a lot of themes who the (GitHub) author is. So I go ahead and notify every single author here. This way we'll see, which GitHub user names don't exist, which ones are active, and which ones are abandoned. A lot of active authors have been already spotted here. But some haven't responded at all.

   * If you are an author of a theme for Cinnamon and still active, please answer to this issue with a +1 or something similar.
   * If you are an author, but your are no longer active, let us know about it.
   * If you are an author, but your (GitHub) name is not listed here or it's wrong, let us know.
   *  If you were notified, but you are not an author of any theme or if you have no idea what is going on here (i.e. you never heard the words Linux Mint, Cinnamon, Themes, Spices), let us know as well, so you won't get notified in the future.

The authors, which responded, will see that the check box besides their name will have a check mark (asap). For themes, which authors can not be detected, the author will be set to none or the theme will be deleted.

- [x] ~~@abnvolk~~ `nonexistent -> none`
- [x] @andr35
- [x] @bimsebasse `abandoned -> none`
- [x] ~~@Brahim~~ `= freemangilgamesh`
- [x] @brownsr
- [x] @cloweling
- [x] @Daniel4lm `abandoned -> none`
- [x] ~~@debimint~~ `nonexistent -> none`
- [x] @edoz90
- [x] @elbullazul
- [x] @feren
- [x] @fmcgorenc `active ->` #41
- [x] ~~@Frankula Wolfenstein~~ `unknown GitHub user name -> none -> mentioned in README`
- [x] @freemangilgamesh
- [x] @frombenny
- [x] @germanfr
- [x] @getkey
- [x] @ioannesrahul `active ->` #203
- [x] ~~@Joseph~~ `abandoned -> none`
- [x] @karthikbhupathy13
- [x] ~~@kessaras~~ `nonexistent -> none`
- [x] @kisskool `abandoned -> none`
- [x] @knightlain
- [x] @madmaxms
- [x] @Merlin77 `abandoned -> none`
- [x] ~~@MztrDLK~~ `nonexistent -> none`
- [x] @Odyseus
- [x] @praveenp
- [x] @Radek71
- [x] ~~@razor~~ `abandoned -> none`
- [x] ~~@satya164~~ `donated -> none`
- [x] ~~@thorin0815~~ `nonexistent -> none`
- [x] @vlad1777d

**Comment by karthikbhupathy13** [comment]
+1

**Comment by Knightlain** [comment]
+1




________________________________

**Comment by madmaxms** [comment]
+1

Am Di, 15. Aug, 2017 um 5:04 schrieb Knightlain 
<notifications@github.com>:

**Comment by praveenp** [comment]
+1

**Comment by getkey** [comment]
Hi!

**Comment by Radek71** [comment]
+1

**Comment by Elbullazul** [comment]
+1

**Comment by satya164** [comment]
heads up, I'm no longer active (fyi my body is active and I'm able to do stuff, some of the days anyways, just that I'm no longer actively making themes 😬)

**Comment by Andr35** [comment]
+1

**Comment by NikoKrause** [comment]
@satya164 
You have one theme [Minty](https://cinnamon-spices.linuxmint.com/themes/view/Minty). What do you want to happen with it? Do you want to do a (basic) support for it? Or do you want the theme to be removed? Or shall we set author to `none` and you to `original_author`, which would mean, that another artist can take over your theme, if he wants to, or it would maybe deleted someday, if it's get too broken or due to lack of interested users (so basically "donate" it)?

**Comment by getkey** [comment]
@NikoKrause Careful with the licenses. In this case I believe it would be okay, because *Minty* is under the GPL, but I don't think you could do that with any theme.

**Comment by frombenny** [comment]
+1

frombenny@gmail.com  Benoit THIBAUD (Cholet - France)

**Comment by NikoKrause** [comment]
@getkey Thanks for pointing this out.

**Comment by satya164** [comment]
@NikoKrause It'd be great if someone takes over! I won't be able to provide support.

**Comment by vlad1777d** [comment]
+1

btw, I already had made some pull requests to this repository =)
If somebody has some suggestions how to make Glass themes look better - feel free and write me.

**Comment by NikoKrause** [comment]
@bimsebasse
@Brahim
@Cloweling
@Daniel4lm
 @fmcgorenc
@Frankula Wolfenstein
@freemangilgamesh
@ioannesrahul
@joseph 
@kisskool 
@Merlin77 
@razor

Are you developers of some of the Cinnamon themes?

**Comment by freemangilgamesh** [comment]
a +1

**Comment by freemangilgamesh** [comment]
Brahim:  a +1

**Comment by NikoKrause** [comment]
Hello everybody,

as it was announced in the [Linux Mint Monthly News - September 2017](http://blog.linuxmint.com/?p=3340): The configuration module for cinnamon spices (applets, desklets, extensions, themes) was completely revamped for Cinnamon 3.6 (Linux Mint 18.3). The themes module now also shows the description, which is stored in the [info.json](https://github.com/linuxmint/cinnamon-spices-themes/blob/88a66d6731a4cf8c937f282cd7b3051cd81e1c27/Eleganse/info.json) file.
For a lot of themes, that's an issue, because it looks like this:
![themes_053](https://user-images.githubusercontent.com/8415124/30616046-35915cb0-9d91-11e7-96f7-7fa6e89a5e62.png)

Please keep the description in your info.json files short (1-2 lines). Text only, no HTML or Links.

You can put all extra info about your theme into a `README.md` file, which you store in the same directory as the `info.json` file, e.g. like in this [example](https://cinnamon-spices.linuxmint.com/themes/view/New-Minty).

I wanted you to know about this issue at an early change to give you enough time to react to this.
I'd appreciate, if you could update your info.json file and shorten the description.

Thanks in advance

**Comment by NikoKrause** [comment]
@satya164 Your Minty theme says "License: GPL". Which versions "GPL-2.0", "GPL-2.0+", "GPL-3.0", "GPL-3.0+"?

**Comment by satya164** [comment]
@NikoKrause it was meant to be `GPL-3.0+`
