### ISSUE TITLE
Fork gnome application grid for Cinnamon

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#226]
I think that gnome application grid is very useful and practical and I think that Cinnamon developers should fork it for Cinnamon: It gives it a more modern and practical outlook.

<a href='https://postimg.org/image/76mwjntvh/' target='_blank'><img src='https://s30.postimg.org/76mwjntvh/ubuntu-desktop-with-numix-square-icon-set-750x46.jpg' border='0' alt='ubuntu-desktop-with-numix-square-icon-set-750x46'/></a>       <a href='https://postimg.org/image/wdxsjwwzh/' target='_blank'><img src='https://s30.postimg.org/wdxsjwwzh/image.png' border='0' alt='image'/></a>   <a href='https://postimg.org/image/omh2lcsu5/' target='_blank'><img src='https://s30.postimg.org/omh2lcsu5/image.png' border='0' alt='image'/></a>

**Comment by brownsr** [comment]
There is a related item in the Roadmap:
menu: consider adopting this layout (https://raw.githubusercontent.com/The-Panacea-Projects/Gnomenu/master/Screenshot.png), same as ours/mintmenu, only better.
There's a well developed 3rd party menu applet in the spices repository which is making this style of menu working available.

**Comment by JosephMcc** [comment]
This request doens't really belong here. I'm pretty sure it's been requested before for Cinnamon itself but you're not likely to see it implemented.
