### ISSUE TITLE
Workflow with CSS preprocessors?

### ISSUE THREAD

**Issue by getkey** [linuxmint/cinnamon-spices-themes#232]
Some of us use CSS preprocessors (PostCSS, Stylus, LESS, SASS, etc.). But this repo can only host CSS which makes the workflow a bit awkward.
When @JosephMcc adapted all themes for Cinnamon 3.4, I had to backport his changes to my repo. If someone wants to contribute to my theme, chances are, they will submit a PR here instead of in my Stylus repo.

I would like to find a solution to make this better. Perhaps something with git submodules?

Pinging a few others preprocessor users (that I know of, sorry for those I left out): @germanfr, @edoz90, @zagortenay333, @Elbullazul, @feren.

**Comment by NikoKrause** [comment]
Can't you create a `src` directory in the same directory as the info.json and host there those files, which are needed to build/create the theme?

The only files, which are downloaded by the users are in the files/UUID directory.

And then add instructions in your README.md file similar as Mint-Y does https://github.com/linuxmint/mint-y-theme/blob/master/README.md

**Comment by feren** [comment]
ping

AFAIK, my theme submissions should just work out-of-the-box, and be editable by just changing parts of cinnamon.css, or at least that was how I had it when Pushing it to this repository...

**Comment by getkey** [comment]
Right, good idea, since only the `files/` directory gets put in the .zip file anyway. 🙂
Closing the issue.
