### ISSUE TITLE
Utnapishtim-Green

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#285]
[Utnapishtim-Green.zip](https://github.com/linuxmint/cinnamon-spices-themes/files/1504425/Utnapishtim-Green.zip)

Download link: https://www.opendesktop.org/s/Cinnamon/p/1200679/
<a href='https://postimg.org/image/feog8qzip/' target='_blank'><img src='https://s8.postimg.org/feog8qzip/Screenshot_from_2017-11-27_02-08-31.png' border='0' alt='Screenshot_from_2017-11-27_02-08-31'/></a>   <a href='https://postimg.org/image/4f38x76jl/' target='_blank'><img src='https://s8.postimg.org/4f38x76jl/image.png' border='0' alt='image'/></a>

```
 * Themes version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon 3.6)
 * Distribution - (Linux Mint 18.3)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of theme**
https://web.facebook.com/bbrahim.salem.5

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by smurphos** [comment]
See the Git Basics section of the README for guidance on how to submit a pull request to add your theme. make sure you read the rest as-well and make sure your theme is correctly packaged.

https://github.com/linuxmint/cinnamon-spices-themes/blob/master/README.md

**Comment by freemangilgamesh** [comment]
I don't know how to upload it! would you do this for me plz?

**Comment by smurphos** [comment]
Instructions on uploading via git are all in the linked document in the Git basics section. They are pretty straightforward to follow - just take it step by step. You are already half way there - you've got a github account and have forked cinnamon-spices-themes. 

You don't want a random having ownership of your theme do you ?? ;-)

**Comment by freemangilgamesh** [comment]
upload it for me plz I trust you guys!

**Comment by freemangilgamesh** [comment]
?

**Comment by JosephMcc** [comment]
Please quit spamming. Instructions are provided on how to work with the repos. If you don't want to do it yourself and want someone to do it for you then have a little patience and see if someone offers.

**Comment by freemangilgamesh** [comment]
cool then!

**Comment by leigh123linux** [comment]
Not an issue.
