### ISSUE TITLE
Upload my Cinnamon theme collection 

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#291]
1. Utnapishtim-Spices: https://www.opendesktop.org/s/Cinnamon/p/1202424/
2. Utnapishtim-Green: https://www.opendesktop.org/s/Cinnamon/p/1200679/
3. Utnapishtim-Blue: https://www.opendesktop.org/s/Cinnamon/p/1202284/

<a href='https://postimg.org/image/wyuedvb1z/' target='_blank'><img src='https://s7.postimg.org/wyuedvb1z/2ba34243d53f42b7f4d10e2558020530287d.jpg' border='0' alt='2ba34243d53f42b7f4d10e2558020530287d'/></a> <a href='https://postimg.org/image/6drvibgef/' target='_blank'><img src='https://s7.postimg.org/6drvibgef/bffbd9a56b2db2a4cb6f6b5bae22948b5929.png' border='0' alt='bffbd9a56b2db2a4cb6f6b5bae22948b5929'/></a>  <a href='https://postimg.org/image/w9bm1j5dj/' target='_blank'><img src='https://s7.postimg.org/w9bm1j5dj/05e8854f8916c4b42cfc0f11ae5c2ef5ba4a.png' border='0' alt='05e8854f8916c4b42cfc0f11ae5c2ef5ba4a'/></a>  <a href='https://postimg.org/image/ifn9ci7nb/' target='_blank'><img src='https://s7.postimg.org/ifn9ci7nb/24a3c2fd3c78f9f1d96b7d3e5c1d22ef0d7f.png' border='0' alt='24a3c2fd3c78f9f1d96b7d3e5c1d22ef0d7f'/></a>

**Comment by freemangilgamesh** [comment]
?

**Comment by germanfr** [comment]
@freemangilgamesh did you make these themes or did you kang them like you did with (at least) **New-Minty with joined menus**? You took it from here, changed it a bit and redistributed it without the license and the unobfuscated source or any reference to it. Doing that it's like saying you made it because you removed @zagortenay333's authorship (and also my part that corresponds to my fork and contributions) and you're breaking the license terms, hence infringing the copyright law.

Please include the license and the source or a reference to it or remove it from [here](https://www.opendesktop.org/p/1208314).

I'm sorry @everyone, I know this is not the place but it is the only way I have to contact him (also he took it from here).

**Comment by leigh123linux** [comment]
@freemangilgamesh Try submitting a pull request for this and make sure you fix the licence first!

**Comment by freemangilgamesh** [comment]
what license! I did not take it from here and I don't know the owner of this theme! I forgot where I got it from and if you want me to delete I will! cool down man!

**Comment by germanfr** [comment]
I was not talking about these, I was talking about `New-Minty with joined menus` that you uploaded [here](https://www.opendesktop.org/p/1208314) and you already removed. Whether you took it from here or from your themes folder, it had a license file you didn't even bother to copy paste or deliberately removed (I don't know).

Please don't misinterpret me. I'm ok with you doing whatever you want with it, including modification, redistribution or selling. It's free software and not me nor the original author can revoke those freedoms. But you can't break the license as you please. If you want to upload it again you have to include the license file at least.

**Comment by freemangilgamesh** [comment]
https://www.opendesktop.org/p/1208506/

**Comment by freemangilgamesh** [comment]
[Utnapishtim-OSX.zip](https://github.com/linuxmint/cinnamon-spices-themes/files/1782180/Utnapishtim-OSX.zip)

this is my new theme <a href='https://postimg.org/image/j9q4yx7cr/' target='_blank'><img src='https://s9.postimg.org/j9q4yx7cr/image.png' border='0' alt='image'/></a>

**Comment by jaszhix** [comment]
If someone uploads (pull requests) it, then they become responsible for it - the commit is tied to them - not you. I think if you want to contribute, [learning how to use git](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) is a good start. Its really not hard, just takes some getting used to. Once you understand version control you'll wonder how you ever lived without it.

> Try submitting a pull request for this and make sure you fix the licence first!
