### ISSUE TITLE
Question - any other selectors deprecated from Cinnamon 3.2 +

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-themes#361]
Hi,

A question for the devs or other theme authors.

`.popup-menu` and `.popup-menu-boxpointer` are noted as deprecated for Cinnamon 3.2+ in the comments of the default theme. Are there any other deprecated selectors floating around the default theme?

For example I can't work out what actually triggers visuals themed under  `.show-processes-dialog-subject`, `.mount-question-dialog-subject`, or `.panel-launcher-add-dialog-entry` and related selectors and was wondering if they are not in use in current cinnamon versions

Thank-you.

**Comment by germanfr** [comment]
There is a [changelog](https://github.com/linuxmint/cinnamon-spices-themes/blob/master/README.md#css-changes-introduced-in-cinnamon-34) in the readme with the deletions and additions but it's not complete for older versions. You can do a grep of the class name in the Cinnamon code or just search for the class name with the Github search engine in the repository to see where or if it is being used.

**Comment by smurphos** [comment]
Thanks for the tip. Works well.

'.panel-launcher-add-dialog-entry' only appears in the default theme - no-where else so I guess can probably be safely written out of themes targeting 3.2+

`.show-processes-dialog-subject` & `.mount-question-dialog-subject` are in the current code.

Reason for asking is I'm planning a conversion of my cinnamon theme template to scss and want to have a tidy base to work from.

A search for 'style_class:' is proving reasonably inforrmative.
