### ISSUE TITLE
Font Scaling - Application Right Click Context Menu Issue

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-themes#366]
@brownsr 

Hi Simon,

I've tagged you as your themes tweaked for text scaling are suffering the same bug as I've just noted in the Cinnamox Themes.

The problem occurs in an application category which has enough apps to have a scroll bar on the right-hand side. Right click fails to open the context menu. On ScaleUp and Graphite-One this is happening at the default text scaling of 1.0. In the Cinnamox Themes they are OK until I raise text scaling to 1.3 or above. If I apply a bigger margin (0.5em rather than 0.2em) to the .menu selector it can trigger at text scaling 1.2.

Any clues?

Edit to add - I think this is something to do with the height of the menu on screen going past a certain point - I'm seeing this on a 1366 x 768 display.

Further edit to add - OK it's a problem in the default theme as-well - it triggers at text scaling factor 1.9 for me.

And one final edit to add - xsession.errors

```
(cinnamon:2822): Clutter-WARNING **: clutter-actor.c:10026: Actor 'StBin' tried to allocate a size of -16.00 x 0.00

(cinnamon:2822): Clutter-CRITICAL **: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
```

![screenshot from 2018-03-08 07-13-18](https://user-images.githubusercontent.com/29017677/37140417-942f74f8-22a9-11e8-8302-97a8775c34b2.png)

**Comment by brownsr** [comment]
No idea right now. Does the same happen in cinnamenu? The current menu is
probably going to get replaced at some time.

**Comment by smurphos** [comment]
It doesn't happen in Cinnamenu, but does in CinnVIIStarkmenu. I'll do some digging - Cinnamenu does something funky with that submenu anyway - I've never managed to work out how to fully theme it Cinnamenu. Anyway this probably should be a Cinnamon issue not a spice issue - it's just these themes surface the bug more quickly than the default, Mixt X or Mint Y.
