### ISSUE TITLE
Silk: Cosmetics & spelling

### ISSUE THREAD

**Issue by ineuw** [linuxmint/cinnamon-spices-themes#37]
First, I love the Silk theme, it is exactly what I've been looking for. 

Just wanted to bring to your attention that when setting a custom icon on the panel menu button, it is  overlapping your animated design. I am unable to hide your logo. Is there a way to do that? Please see the attached image.

![selection_027](https://cloud.githubusercontent.com/assets/10367016/22854417/3c3ba26c-f03c-11e6-956d-71bdb03509ad.jpg)

Also, to bring to your attention that on the Silk theme web page, there is a typo in the description below the screen display.  I believe it should be "- simple flat theme"  and not "- simle flat theme".

[https://cinnamon-spices.linuxmint.com/themes/view/Silk],

**Comment by JosephMcc** [comment]
I fixed the title but please use the theme names in the title when reporting problems.

**Comment by Fleury93** [comment]
I love this theme too. It's one of my favourite themes. But default icon cannot hide or overlap. It's annoying I need a thin system bar but menu icon is too large so therefore I don't use this theme. It's so pitty.

Thank you for your work.

**Comment by brownsr** [comment]
Closing:   this is actually a problem that you can solve yourself.  Use the 'spacer' applet, it's a bit fiddly as it is invisible once added, but manageable - the green line mouseover in this theme will help you find it.  Add it to the panel, then drag it over the panel decoration that is conflicting with the menu, in edit mode.  It will bump the menu out of the way and as it is invisible it will not mess up the decoration.  Leave edit mode.  If you need more space then right click on it and configure it to give you more space.
