### ISSUE TITLE
To Clement: Upload 2 versions of a theme at once to Cinnamon Spices!!

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#378]
Utnapishtim-Sleek: https://www.opendesktop.org/p/1224014/
<a href='https://postimg.org/image/f3jv9z89h/' target='_blank'><img src='https://s18.postimg.org/f3jv9z89h/image.png' border='0' alt='image'/></a>
MGSE-Unity: https://www.opendesktop.org/p/1208506/
<a href='https://postimg.org/image/mjj4vvykl/' target='_blank'><img src='https://s18.postimg.org/mjj4vvykl/image.png' border='0' alt='image'/></a>

**Comment by JosephMcc** [comment]
Sorry but uploading random themes from people that we then have to maintain isn't really what we are here to do. We have at least some expectation from users to upload and maintain their themes.

**Comment by freemangilgamesh** [comment]
same song and dance!!
