### ISSUE TITLE
What's wrong Linux Mint github guys!!!

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#389]
I have been trying to upload themes and you kept declining theme. My last theme is based on a theme you just aploaded to Cinnamon "qob" https://cinnamon-spices.linuxmint.com/themes/view/qob  this theme gets accepted but mine not and you gave me errors you are responsible for!!!!!!!!!!!!I did not touch the sections you are talking about it!!!!!!!!!!

**Comment by NikoKrause** [comment]
Please learn how to use `git` (GitHub is only a hosting-service for git). It's a command used in the terminal. (Don't upload files via the GitHub website)

After you're done learning git, do a clean Pull Request, i.e. only 1 commit. E.g. this one has 15 commits: https://github.com/linuxmint/cinnamon-spices-themes/pull/388

Also 1 Pull Request should only contain 1 theme. Your Pull Request contains several themes (ChinVat, MGSE-Unity, Nexus, etc.)

Keep your themes clean from files, which are not needed, e.g. Vivaldi-ZorinOS.zip. Only include files, which are needed for the theme to work.

For example this https://github.com/linuxmint/cinnamon-spices-themes/pull/300 is a good Pull Request as described.

Read the README.md. It contains informations on which files and directories are mandatory, plus it contains some basic informations about git: https://github.com/linuxmint/cinnamon-spices-themes/blob/master/README.md

Here's another Git-Tutorial: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/28

Practice with those tutorials. If there's something in the tutorials, you don't understand or if you run into some problems with git, describe your git-problem and you'll get answers.

**Comment by freemangilgamesh** [comment]
same song and dance!! I had enough of you guys!! you're supposed to give explanation when declinng a theme. I pulled a request for Chinvat only!!

**Comment by NikoKrause** [comment]
If I take a look at your Pull Request for Chinvat, that's what I see:
![screenshot-area-2018-04-11-162913](https://user-images.githubusercontent.com/8415124/38623330-aea8e960-3da5-11e8-80a4-30a343c1a3dc.png)

`Commits 15` and `Files Changed 246`

Then I press on the tab with `Files Changed 246` and scroll to the very bottom:
![screenshot-area-2018-04-11-163315](https://user-images.githubusercontent.com/8415124/38623500-1b11a240-3da6-11e8-89e2-ff3e9680c785.png)

I see files as `Vivaldi-ZorinOS.zip` `Utnapshtim-colors.zip` etc.

So those are not Chinvat only files.

**Comment by freemangilgamesh** [comment]
you gave me errors for Chinvat only guys!!

**Comment by NikoKrause** [comment]
Which errors?

**Comment by freemangilgamesh** [comment]
cinnamon.css errors <a href='https://postimg.cc/image/54bal6ky5/' target='_blank'><img src='https://s14.postimg.cc/54bal6ky5/image.png' border='0' alt='image'/></a>

**Comment by NikoKrause** [comment]
That's a bot. Please ignore the bot and focus on the stuff I told you above.
Do some git tutorials.

**Comment by freemangilgamesh** [comment]
last time you bot friend said give me a clean css file and you'll be fine and now you are asking me to learn kung fu!! jeeez louise!!

**Comment by freemangilgamesh** [comment]
I can see you have deleted these botilcious errors now!! “Something is rotten in the state of Denmark”

**Comment by NikoKrause** [comment]
I tried to help you. I pointed out the points here https://github.com/linuxmint/cinnamon-spices-themes/issues/389#issuecomment-380468531, why your PR has been declined.

I didn't asked you to learn kung fu, but to learn the basics of uploading and maintaining your theme. I even pointed out some specific tutorials. I have the feeling, that you don't seem to take my help seriously.

**Comment by freemangilgamesh** [comment]
man I read these tutorials and I followed them literally!!

**Comment by freemangilgamesh** [comment]
why don't you just add upload theme button to Cinnamon Spices then you review these themes before accepting them!!

**Comment by leigh123linux** [comment]
None> why don't you just add upload theme button to Cinnamon Spices then you review these themes before accepting them!!
