### ISSUE TITLE
Question - View on uploading third party themes

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-spices-themes#397]
Hi,

I was wondering what the view is on Cinnamon Spices hosting builds of third-party themes with little or no modification assuming that they are clearly attributed to the original source and where applicable appropriate licensing info is included in the theme?

I've got two themes in mind with different reasons for wanting to host builds on Cinnamon Spices.

1) Adapta - the developer is imminently going to drop support for GTK3.18 and I think the outcome is that any Mint 18 users who installed the theme and update it via PPA will suddenly find the GTK theme no longer works. I'm considering forking the theme with a view to making a build containing just the Metacity, GTK2, 3.18, 3.20, 3.22 and Cinnamon themes with a view to hosting those builds on Cinnamon Spices.

2) Materia - I've recently contributed a Cinnamon theme and some Nemo theming to Materia and it would be nice to share that work here along with again the Metacity, GTK2, 3.18, 3.20, and 3.22 themes. I appreciate that there are many similarities between Materia and Adapta, the latter being forked from the former so may opt for one or two colored versions of Materia.

Grateful for your thoughts.

**Comment by xenopeek** [comment]
Themes in question:
https://github.com/adapta-project/adapta-gtk-theme
https://github.com/nana-4/materia-theme

Both licensed under GPLv2, which in summary gives these requirements for forking: https://tldrlegal.com/license/gnu-general-public-license-v2

**Comment by NikoKrause** [comment]
If the themes are licensed under GPLv2, then everything seems fine.
You're allowed to fork them as long as you keep the license.

I don't see why you can't upload them, if you want to maintain them.

**Comment by smurphos** [comment]
Thanks for the clarification @NikoKrause. Good to know.
