### ISSUE TITLE
My Linux Mint themes

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon-spices-themes#4]
1. Silk-blue https://www.cinnamon-look.org/p/1167091/

<a href='https://postimg.org/image/ubcla35w7/' target='_blank'><img src='https://s23.postimg.org/ubcla35w7/3ba395e49962a8dd4ecb2454e7fc8b0b7395.png' border='0' alt='postimage'/></a>
2. Windows10-optimized-v2  https://www.cinnamon-look.org/p/1167062/

<a href='https://postimg.org/image/h3mip6ltz/' target='_blank'><img src='https://s23.postimg.org/h3mip6ltz/5107baf8990851ca28e28425a5ef032ff66e.png' border='0' alt='postimage'/></a>

**Comment by JosephMcc** [comment]
I'm a little confused. What's the point of this issue? It doesn't look like a bug, feature request, or anything really.

**Comment by freemangilgamesh** [comment]
because I can't upload my themes to Cinnamon spices and they told me to upload them here

**Comment by JosephMcc** [comment]
You need to use github and make a pull request to add new themes.
