### ISSUE TITLE
Void: Volume slider not visible in the background

### ISSUE THREAD

**Issue by swarnendubiswas** [linuxmint/cinnamon-spices-themes#400]
```
 * Themes version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version) Cinnamon 3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Ubuntu 18.04
 * Graphics hardware *and* driver used 
[glass.log](https://github.com/linuxmint/cinnamon-spices-themes/files/1913846/glass.log)

 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of theme**
@

**Issue**

![20180415_230903](https://user-images.githubusercontent.com/7343807/38789823-7b80b828-4102-11e8-9c5f-81b176f89abc.jpg)

**Steps to reproduce**
1) Enable the Void theme.
2) Change the volume using multimedia keys from the keyboard.

**Expected behaviour**
The slider should be legible.

**Other information**
The slider is not legible against the background.

**Comment by smurphos** [comment]
There is a lot broken in this theme. I've just made a start on fixing it.
