### ISSUE TITLE
Spices themes and xlets licenses

### ISSUE THREAD

**Issue by germanfr** [linuxmint/cinnamon-spices-themes#402]
Hey, I don't want to be a grinch, but you are taking very lightly the license terms of the themes and xlets since you moved from the old website to github. Even I did it myself yesterday without thinking by updating an unlicensed applet (sorry author).

The license of the Void theme is a [CC-by-nc-nd](https://creativecommons.org/licenses/by-nc-nd/3.0/) as stated [here](https://luisrafaelgalvez.deviantart.com/art/Void-Cinnamon-310742162), which means you can't redistribute derived works, and that is exactly what you are doing here #401. I don't know if you contacted the author, but he didn't even say anything in #221 and you took that as a "we can do what we want". Some xlets don't even have a license, which means the most restrictive terms apply: you can distribute them because they gave you permission, but you can't touch the code (not even upload it to Github in the first place). 

**I suggest that only free software is allowed here, or at least that you indicate somehow the license of each xlet**, since one of the purposes of having these repositories was to enable the community to maintain the xlets to keep them working if the author abandoned them.

**Comment by NikoKrause** [comment]
Hey, I started to add license infos to the `info.json` files in the past for those xlets/themes, which I could find: https://github.com/linuxmint/cinnamon-spices-themes/search?l=JSON&q=license&type=

It would be nice, if you could help figure the rest out.
There are a bunch of xlets, which have been donated. So I think it's ok for those (if they don't have a license) to add a GPL license (which Cinnamon uses).

For themes/xlets with a license, which does not allow modifications (as the Void theme): We should delete them.

Does this sound ok to you?

**Comment by NikoKrause** [comment]
Pinging authors for license infos:
Please at the `license` of your themes to the `info.json` file as it's done already in this themes: https://github.com/linuxmint/cinnamon-spices-themes/search?l=JSON&q=license&type=

- [ ] @frombenny (Ambiance-Crunchy)
- [ ] @feren  (Ambiance Minty)
- [ ] @brownsr (BelaLugosi, Graphite-*)
- [ ] @fmcgorenc (Blue-Moon, Dark-Moon)
- [ ] @Cloweling (CBlack)
- [ ] @Andr35 (Carta)
- [ ] @smurphos  (Cinnamox-*)
- [ ] @getkey (Discreet Flat)
- [ ] @knightlain (Escarlata)
- [ ] @vlad1777d (Glass-*)
- [ ] @madmaxms (Jade-1)
- [ ] @smilesbright (LM-Light-Panel)


Themes with no authors and no license info:
- [ ] Android-Holo (delete as Void: https://luisrafaelgalvez.deviantart.com/art/Android-Holo-cinnamon-theme-325297318)
- [ ] Baldr
- [ ] Blue mint
- [ ] Facebook
- [ ] Faience
- [ ] Jet-Gray
- [ ] Kiss-Kool-Viper

------------- no info.json file ---------
- [ ] Chinvat


... to be continued

**Comment by germanfr** [comment]
Faience comes from [here](https://bimsebasse.deviantart.com/art/Faience-Cinnamon-343219486), and the autor says it is a port from [the Faience Gnome shell theme](https://tiheum.deviantart.com/art/GTK3-Gnome-Shell-Faience-255097456), which is GPL3, so I guess it can be marked as GPL.

**Comment by germanfr** [comment]
I contacted the author of Faience, Loki, Baldr, Tyr-himinn and Tyr-jord via email and he says we can mark them as GPLv3.

<img height="720" src="https://user-images.githubusercontent.com/10391266/38892736-64b51f8a-4288-11e8-84e8-b40430c40565.png"/>

**Comment by vlad1777d** [comment]
Maybe it's not right place to ask, but which license is better to use ?
GPL3, or CC-BY ?
Or, maybe, CC-BY-NC ?

Thanks.

**Comment by germanfr** [comment]
@vlad1777d CC licenses are not recommended for software. Use a GPL instead if you want to reincorporate fixes others make in forks of your xlets and you don't want others to make privative software from your effort.

**Comment by vlad1777d** [comment]
@germanfr , thanks.

Well, than I'll add GPL to it.
I'll add them soon (if will not forget about it).

**Comment by getkey** [comment]
2 things:

- I think a copy of the license need to be shipped with the source code too (is that right?)
- many themes are based on the default theme's code which is licensed under the GPL (?). To give more freedom to the themers, it would be nice to give it a more permissive license like the MIT or even put it in the public domain. Since the CSS selectors are undocumented, most people have no choice but to modify the default theme.

Originally, that's the case of Discreet Flat, so I guess it's automatically GPL'd. However if I am given the choice I'd rather have it be under the MPLv2.

**Comment by feren** [comment]
For GPL, yeah, I'm pretty sure you have to supply a copy of the license Ts&Cs as a file alongside the contents that are GPL licensed...

**Comment by getkey** [comment]
Follow-up: the default cinnamon theme is in [this GPL'd repo](https://github.com/linuxmint/Cinnamon/tree/master/data/theme).
