### ISSUE TITLE
[Mint-Y-Yltra-Dark] Control theming doesn't apply correctly.

### ISSUE THREAD

**Issue by Draconicrose** [linuxmint/cinnamon-spices-themes#431]
```
 * Mint-Y-Yltra-Dark theme v0.6.8.6
 * Cinnamon 3.8.7
 * Mint 19
 * NVidia GT 730 | nvidia-driver-390
 * https://dpaste.de/0a18 (glass log)
 * https://www.dropbox.com/s/5anah10h4gbov6b/.xsession-errors (xsession-errors)

 ```
**Notify author of theme**
@

**Issue**
When applying the Mint-Y-Yltra-Dark theme to the Controls section, the theme breaks, displaying only text.

**Steps to reproduce**
Download Mint-Y-Yltra-Dark, apply theme to the Controls section of the Themes dialogue. 

**Expected behaviour**
The controls inside the window would turn blue for the activated tab, like in Mint-Y-Dark, but in a blue color.

**Other information**
I've posted about [this on Reddit](https://www.reddit.com/r/linuxmint/comments/8wwcbk/all_custom_themes_broken/) and it was suggested that this might be an issue with the proper packages not being installed. However, I've tried this on two computers, one with a fresh Mint 19 install, the other upgraded from 18.3, and the same behavior happens in both of them. I believe the theme might not have been fully updated for Cinnamon 3.8, despite what the Spices site says.

**Comment by smurphos** [comment]
It's not been updated to support GTK 3.22.x yet. I had committed sometime ago to looking at these to help out but then other life commitments got in the way. It's still on my todo list.

**Comment by Draconicrose** [comment]
Is there any resource I could use to attempt this conversion myself?

**Comment by smurphos** [comment]
@Draconicrose if you refresh your cache in the Themes app and update Mint-Y-Yltra-Dark the new version with GTK3.22 support added should download. Mint-Y-Yltra-Light has also been updated.

**Comment by Draconicrose** [comment]
Awesome! Thank you very much.

**Comment by Draconicrose** [comment]
The theme still breaks in the same way when viewing windows with elevated privileges (such as Synaptic package Manager, or a folder as root)

**Comment by smurphos** [comment]
The same way or does is the default light Mint-Y theme used for root apps?

**Comment by Draconicrose** [comment]
Well, I think I found a slight problem: https://dpaste.de/jisk

Apparently there's no usr/share/themes. Does that mean the system doesn't
know what themes to fall back to?

Creating the symlink and restarting cinnamon didn't fix the theming issue
in synaptic.
https://framapic.org/QeGNmIcqDpmZ/onQ4B9giU5ZS.png

**Comment by smurphos** [comment]
Sorry - my bad - both sets of instructions had typos..

Corrected - 

To create the symlink

`sudo ln -s ~/.themes/Mint-Y-Yltra-Dark /usr/share/themes/`

To check the contents of /usr/share/themes

`ls /usr/share/themes'

**Comment by Draconicrose** [comment]
`draconicrose@DragonNest ~ $ ls /usr/share/themes
 Adwaita       'Linux Mint'      Mint-X-Pink     Mint-Y-Yltra-Dark
 Adwaita-dark   Mint-X           Mint-X-Purple   Mist
 Clearlooks     Mint-X-Aqua      Mint-X-Red      oxygen-gtk
 Crux           Mint-X-Blue      Mint-X-Sand     Raleigh
 Default        Mint-X-Brown     Mint-X-Teal     Redmond
 Emacs          Mint-X-compact   Mint-Y          ThinIce
 HighContrast   Mint-X-Grey      Mint-Y-Dark
 Industrial     Mint-X-Orange    Mint-Y-Darker
`
Obviously now the symlink fails to create because apparently Yltra dark is already in there.

**Comment by smurphos** [comment]
I'm at a bit of a loss to be honest. The contents of `/usr/share/themes` looks to be as expected.

Do you have a /home/root directory? There shouldn't be if this is a fresh install of 19. There might be if you upgraded from 18.x. If there is check if there is a .themes folder. If there is delete it.

Can you also log out, log back in, open Synaptic and then report back output of `cat ~/.xsession-errors`.

**Comment by Draconicrose** [comment]
I don't have a /home/root directory, even though this was an upgraded mint 18.3. 

Output: https://dpaste.de/RvY8

**Comment by smurphos** [comment]
There are no theme parsing errors noted.

Double check that the symlink is correct
`ls /usr/share/themes/Mint-Y-Yltra-Dark`

Mine -

```
cinnamon  gtk-2.0  gtk-3.22     LICENSE     metadata.json
CREDITS   gtk-3.0  index.theme  metacity-1
```

Confirm Synaptic version 
`apt version synaptic`

It should be `0.84.3linuxmint1+tara`

Do you have the same issue opening Nemo as root (right click in Nemo pane, select open as root)

Reinstall stick themes
`apt install --reinstall mint-themes gnome-themes-extra-data`

**Comment by smurphos** [comment]
Got there in the end.... ;-)

It's a bit weird that the original symlink didn't properly mirror the target directory but there we go.

If you are testing themes downloaded via the Themes app and they include a GTK theme then you do need to create a symlink for them to apply to root apps. The Themes app will always install into ~/.themes

If you are installing themes by any other manual method you can choose to install them directly to /usr/share/themes. Themes installed via PPA or from the repos will normally install straight to /usr/share/themes.

**Comment by Draconicrose** [comment]
Ah okay then. Thank you for all your help!
