### ISSUE TITLE
Pruning out less popular themes

### ISSUE THREAD

**Issue by brownsr** [linuxmint/cinnamon-spices-themes#446]
@vlad1777d 

I am currently pruning out some of the less popular Cinnamon themes, and your glass themes are among the lowest rated.  Sorry !  Perhaps you might like to think about pruning a number out, perhaps reducing to just a couple ?

Regards

Simon

**Comment by smurphos** [comment]
Simon - a few more potential candidates to consider for removal.

ChromeOS - GTK.3.22 is broken as is Metacity. Author does maintain the theme at https://github.com/B00merang-Project/Chrome-OS, but hasn't updated here

Windows-10 - GTK3.22 is slightly broken as is Metacity. Author does maintain the theme at https://github.com/B00merang-Project/Windows-10, but hasn't updated here

Mint-Y-Blue and Mint-Y-Dark-Blue - very similar to the more popular Mint-Y-Yltra-Dark which now has working GTK3.22 support.

Jet-Gray - No GTK3.22 support, and GTK3.18 is not great.

All of the Mint-XP variants - no GTK3.22 support. 

Vivaldi-Zorin-OS - no GTK3.22 support.

Spider-Void - no GTK3.22 support.

I'm planning on taking a look at Ambiance Crunchy to see if GTK3.22 support can be ported across from the current upstream.

**Comment by vlad1777d** [comment]
@brownsr , yeah, you can remove any you want )
