### ISSUE TITLE
Chrome OS theme: UI problems

### ISSUE THREAD

**Issue by MrElectroNick** [linuxmint/cinnamon-spices-themes#46]
Menu button wasn't customized - but still holds mint logo and "menu" text but has to be 9 dots as on screenshot of theme
![chrome-os-theme-issue-black-font-color-taskbar](https://cloud.githubusercontent.com/assets/3267843/22856872/431fcfb0-f0a3-11e6-9e5e-cc1291acb69c.png)

Most icons look good - but performance monitor graphs are moved up
![chrome-os-theme-issue-some-applets-not-aligned-properly](https://cloud.githubusercontent.com/assets/3267843/22856888/67ecf6b0-f0a3-11e6-85b3-6d02dd1253e3.png)

Textbox looks ugly - text is cropped
![chrome-os-theme-alt f2](https://cloud.githubusercontent.com/assets/3267843/22856890/6a7be332-f0a3-11e6-86a8-5853d37e0aec.png)

**Comment by Elbullazul** [comment]
@MrElectroNick thanks for the bug report, I'll fix this and sumbit a PR soon enough

**Comment by MrElectroNick** [comment]
@Elbullazul 

With menu button - I thought changing theme will automatically change an icon too - as in "non configured" state it probably should do what theme suggest

Applet I completely happy with is this one: https://cinnamon-spices.linuxmint.com/applets/view/12

It's quite old however look best on my taste :-)

**Comment by MrElectroNick** [comment]
BTW - there's a pull request for your theme waiting: https://github.com/linuxmint/cinnamon-spices-themes/pull/53

Might be related to what I reported.

Anyway - your theme is one of the best - which I'd more likely to use if issues are fixed :smile:

**Comment by brownsr** [comment]
Closing:  
1) custom icon can be added by menu - configure
2) the 'run' appearance seems fine when I just tried it.
3) This applet looks like this in every theme I have tried it in, including the default theme, so it would appear to be an applet rather than a theme problem.

**Comment by MrElectroNick** [comment]
@Elbullazul @brownsr - You answered 3 of 4 points - what about this one?:

https://cloud.githubusercontent.com/assets/3267843/22856872/431fcfb0-f0a3-11e6-9e5e-cc1291acb69c.png

**Comment by Elbullazul** [comment]
@MrElectroNick latest version fixes this but I haven't updated the spices version. should be done by tomorrow

**Comment by MrElectroNick** [comment]
@Elbullazul Cool! Thanks!
