### ISSUE TITLE
It is possible to realize a much more compact version for small monitors because it is one of the best themes

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon-spices-themes#466]
It is possible to realize a much more compact version for small monitors because it is one of the best themes

![schermata del 2018-11-04 14-01-11](https://user-images.githubusercontent.com/26720956/47964610-ed60be00-e03c-11e8-98fb-224770418a54.png)

Cinnamon 3.8.9
Fedora 29 x86-64
Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
AMD Mars LE [Radeon HD 8530M / R5 M240] driver: radeon v: kernel 
x11 server: Fedora Project X.org 1.20.2 
ati,modesetting,radeon unloaded: fbdev,vesa resolution: 1366x768~60Hz 
Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.2.2

**Comment by brownsr** [comment]
which theme do you have in mind ?
