### ISSUE TITLE
Adapta themes - shutdown/logout buttons unnecessarily widening menu in cinnamon 4.0.0

### ISSUE THREAD

**Issue by ncpa0cpl** [linuxmint/cinnamon-spices-themes#469]
After upgrading cinnamn to version 4.0.0 menu layout slightly changes, shutdown, logout, switch user buttons are placed next to the search bar now, this makes menu widen far too much (like it takes half of my screen width now) and creates unused space under these buttons. I imagine this could be fixed by simply squeezing search bar and buttons a little. Search bar could be 2/3 of it's width and buttons 1/3.
I'm using Adapta-Nokto-Eta, but all of Adapta themes seems to have this issue.

**Comment by smurphos** [comment]
Hi, fixes for Cinnamon 4 should be uploaded in the next week or so. It's on
my radar.
