### ISSUE TITLE
Can't Change Icon Spacing in System Tray (Carta Theme)

### ISSUE THREAD

**Issue by mfreeman-xtivia** [linuxmint/cinnamon-spices-themes#483]
The spacing between the icons in the system tray when using Carta theme with Cinnamon 3.8 is EXTREMELY tight and there doesnt seem to be any setting that i can use in cinnamon.css to provide more spacing between the icons...

![image](https://user-images.githubusercontent.com/10734467/48915879-eeb82600-ee45-11e8-826d-1617544324ba.png)

**Comment by jaszhix** [comment]
The systray spacing is controlled by the layout manager on a Clutter.Actor, not St.Widget, so its not theme-able. I don't think there's a way to give that control to themes without re-writing some of the systray applet.

See https://github.com/linuxmint/Cinnamon/commit/fcd55ee7cfebc0a9e08ff8f06649c6f0fa1ade59
