### ISSUE TITLE
Authors of Mint-Y variant themes - do you still want them ?

### ISSUE THREAD

**Issue by brownsr** [linuxmint/cinnamon-spices-themes#506]
Mint-Y variant theme authors.  In the latest version of the Mint-Y themes that is in the Mint 19.1 Beta there are a variety of colour themes and light/dark variants.  Do you still want to keep your theme now there is an 'official' version that is likely to be very similar ?  Do check the new Mint-Y variants out and let me know.

@otavioschwanck
@karthikbhupathy13 

Note: Mint-Y-Dark-Blue, Mint-Y-Yltra-Dark and Mint-Y-Yltra-Light don't have active authors

@smurphos As you have maintained the Yltra themes recently, what is your view on these ?  

Regards

Simon

**Comment by smurphos** [comment]
@brownsr as mentioned before I've go no particular attachment to the Yltra versions and they have no  real difference from current Mint Y Blue other than ongoing GTK3.18 support for 18.x users. They also allow access to a Mint-Y for other Cinnamon using distros that don't ship mint-themes.

If you want to keep them I'm happy to maintain them. Intention would be to base the Cinnamon.css on current Mint Y whilst retaining support for at least 18.1 onwards. If you think they should go I've got no issue with that either.
