### ISSUE TITLE
CBlack Cinnamon 4.0 update

### ISSUE THREAD

**Issue by jonnyabu1** [linuxmint/cinnamon-spices-themes#514]
CBlack Theme - Cinnamon

@Cloweling

Before the last update earlier Dec 2018 the menu and taskbar for Cinnamon were nicely black but after updating them now they're a fairly dark grey, but not black.  At least on my home and work workstations.  I don't know if that was planned or not given that as far back as I remember it's been black ( my preference but maybe not yours ).  Would it be possible to go back to the black scheme?

Or if you desire it to be dark grey, can a black variant be done?  I know there's CBlack-Dark for controls but maybe CBlack-Dark-Complete or something.  

In any case, thanks for the theme over the years!  I've used it for quite a long time, as far back as I recall using Cinnamon so I've enjoyed.  

Thanks!

**Comment by Cloweling** [comment]
@jonnyabu1 First of all thank you very much for appreciating my theme, previously I had it totally black the subject, to be exact I had it with rgba (20, 20, 20, 1) but as I decided to use the linux mint theme, the opaque black color was adapted better, I put it in the color rgba (47, 47, 47, 1). To change the color we can do two things:

1. Wait for about 2 weeks and I make the new topic.
2. You enter the folder .themes / CBlack / cinnamon / and open the file cinnamon.css and with any text editor you replace
47, 47, 47 by 20, 20, 20 and ready would be to your liking.

Greetings I hope your answer.

**Comment by jonnyabu1** [comment]
Perfect.  Thank you!  Changing to 20, 20, 20 works perfectly and achieves what I was looking for.  Appreciate it!

**Comment by jonnyabu1** [comment]
Closing the topic as the provided answer achieved the desired results
