### ISSUE TITLE
Adapta-Nokto Volume icon not centered

### ISSUE THREAD

**Issue by VernonSV** [linuxmint/cinnamon-spices-themes#546]
Last-edited: 1542521204
Cinnamon 4.0.9 Tessa
Linux Mint 19.1
Intel© Celeron© CPU  N2840  @ 2.16GHz × 2 & Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display

The issue happens on both Adapta-Nokto and Adapta-Nokto-Eta, with stock icons or third party icons. I've also changed the text scaling factor but nothing changed, neither with font size.
Here are some screenshots on how it looks with the theme and how it looks on stock.
![captura de pantalla de 2019-01-11 11-39-44](https://user-images.githubusercontent.com/43186467/51050969-0e431380-1598-11e9-8347-ed89120ca69f.png)
![captura de pantalla de 2019-01-11 11-56-02](https://user-images.githubusercontent.com/43186467/51050978-1602b800-1598-11e9-9116-c24e3a667aa4.png)

**Comment by smurphos** [comment]
Thanks for the report @VernonSV - will be fixed in the next update.
