### ISSUE TITLE
Adapta-Nokto: input method framework dropdown not showing

### ISSUE THREAD

**Issue by sheodox** [linuxmint/cinnamon-spices-themes#565]
```
 * Themes version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version: 4.0.9
 * Distribution - Mint 19.1
 * Graphics AMD Vega 56 Mesa 19.1

 ```

**Notify author of theme**
@smurphos 

**Issue**
On the Input Method page in settings, using Adapta-Nokto controls the title bar which has a dropdown for the input method framework as well as window controls doesn't show up. Here's a screenshot with Adapta-Nokto and Adwaita
![image](https://user-images.githubusercontent.com/3468630/54470394-d6fa0a00-4774-11e9-9fda-405f309ae871.png)

**Comment by smurphos** [comment]
Thanks for the report @sheodox. Reproduced. I'll look into it.

**Comment by sheodox** [comment]
Thanks @smurphos! Is this available through the themes menu in Mint now or do these updates get scheduled for release later? I saw there was an update but don't see the fix included after updating.

**Comment by smurphos** [comment]
It should be, but I've got the same issue - it's still downloading the previous version both via the themes module and directly from Cinnamon Spices.  I've not seen that before.

If you want to manually apply the fix it's in the `~/.themes/Adapta-Nokto/gtk-3.22/gtk.css` file.

Line 759 in the old version reads.
```
`.titlebar, headerbar { background-color: #222d32; background-clip: border-box; color: rgba(207, 216, 220, 0.87); }
```
Change it to
```
.titlebar, headerbar { background-color: #222d32; background-clip: border-box; min-height: 42px; color: rgba(207, 216, 220, 0.87); }
```
Save the file and hit Ctrl-Alt-Esc to restart Cinnamon.

**Comment by smurphos** [comment]
It's some sort of caching issue with Cinnamon Spices website.

'https://cinnamon-spices.linuxmint.com/files/themes/Adapta-Nokto.zip' downloads the old version

'https://cinnamon-spices.linuxmint.com/files/themes/Adapta-Nokto.zip?' gets the new.

**Comment by smurphos** [comment]
So running `sudo systemd-resolve --flush-caches` allowed the Themes module to download the new version.

For direct download from the Spices website I also needed to close and clean history/cache in my browser.
