### ISSUE TITLE
Discreet Flat - OSD sound icon doesn't have a bar

### ISSUE THREAD

**Issue by yigitdnz** [linuxmint/cinnamon-spices-themes#569]
* Theme version 1.2.0
 * Cinnamon 4.0.10
 * Linux Mint 19.1 and Arch Linux (the issue exists on both)

**Issue**
The large sound icon that appears in the middle of the screen when you use the volume control buttons on a keyboard doesn't have the bar that indicates the volume level.

![5](https://user-images.githubusercontent.com/8185376/56997454-7f8eec80-6bb0-11e9-8aec-bd3bb5c7f93c.png)

**Steps to reproduce**
Increase or decrease volume using volume control buttons on a keyboard or on a laptop.

**Expected behaviour**
This image is from qob theme.

![6](https://user-images.githubusercontent.com/8185376/56997483-99c8ca80-6bb0-11e9-8edc-211858100d88.png)

**Comment by getkey** [comment]
Thanks for the detailed bug report! I'm fixing this in #582.

If you notice new bugs, when you open an issue, don't hesitate to ping me with @getkey. :wink: I don't look at the open issues often so it's a faster way to get my attention.
