### ISSUE TITLE
CBlue: Modification not supported.

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-spices-themes#571]
Hello,

I don't know why but commit #570 has not been taken into consideration. Do I have to do it again?

Thanks.

Edit: On github, changes are validated but not on https://cinnamon-spices.linuxmint.com/themes/view/CBlue.

**Comment by Bundy01** [comment]
Hi,

it's back to normal. A latency problem with the site?

**Comment by smurphos** [comment]
I've had the issue myself the last couple of spice updates I've had merged. Deleting local cache andf force refreshing the page in the browser seems to help for downloading the zip from the Spices website. Downloading via the Themes module seems to takes a day or two to sort itself out.

**Comment by Bundy01** [comment]
**@smurphos: Thank you for the feedback.**

 I leave the issue open, if someone thinks it is useful they can close it or ask me to do so.
