### ISSUE TITLE
CBlue: the update on cinnamon-spices.linuxmint.com is not done.

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-spices-themes#580]
```
 * Themes: CBlue and other?
 * Cinnamon version (4.2.3)
 * Distribution - (Arch)
 ```

**Issue**

Hi,

It has been going on for several PRs, the updates are not done on the site **cinnamon-spices.linuxmint.com**. Only the README is updated…

It takes several days for this to be taken into account. It's boring for those who use the applet **Spicies Update**.

**Steps to reproduce**

To each PR

**Comment by claudiux** [comment]
@Bundy01 Add a question mark to the end of the download link. [https://cinnamon-spices.linuxmint.com/files/themes/CBlue.zip?](https://cinnamon-spices.linuxmint.com/files/themes/CBlue.zip?)

**Comment by Bundy01** [comment]
Hi claudiux,

the address provided actually works.
Could you please modify your applet so that it works for all themes?

Do you know the reason for this bug? Maybe get in touch with the site's developers?

**Comment by claudiux** [comment]
@Bundy01  When you put a question mark to the end of an URL, you force the server to answer to a particular request. Thus, the server sends the latest version of the file, by-passing all cache.

I don't know where is the source code of the Spices site. I have already suggested to put a question mark to the end of all Download links.

My applet? Do you think about [SpicesUpdate@claudiux](https://cinnamon-spices.linuxmint.com/applets/view/309)? It already uses question marks to download json files containing the xlets references.

**Comment by Bundy01** [comment]
Thank you for the explanations.

I was actually talking about this applet. However, following the PR, SpicesUpdate informs me of the update but the changes are not applied.

**Comment by claudiux** [comment]
@Bundy01 Do you have the latest version (2.1.0) of Spices Update?

**Comment by Bundy01** [comment]
Yes, I have the latest version (2.1.0)

Le mer. 31 juil. 2019 à 3:38, claudiux <notifications@github.com> a 
écrit :

**Comment by claudiux** [comment]
I propose the PR above to fix this issue.

**Comment by Bundy01** [comment]
Ok,

thanks for your PR, I didn't know which file was handling it.

**Comment by claudiux** [comment]
@Bundy01 There are some changes in my PR https://github.com/linuxmint/cinnamon/pull/8746, which solves the problem with Cinnamon settings. But the problem with the Download button of the Spices web site is still present.

**Comment by Bundy01** [comment]
@claudiux 

Hi,
you were faster than me :)
I wanted to let you know that your old PR wasn't working.
I tested the last one and it works with Cinnamon's settings.
