### ISSUE TITLE
Possible no continuation

### ISSUE THREAD

**Issue by ubuntucinnamonremix** [linuxmint/cinnamon-spices-themes#590]
We want to place the Adapta-Nokto theme in the Ubuntu Cinnamon remix. However we do not know its future due to the Adapta project being discontinued and no support past Cinnamon 4.2. We would like to know what is going on with the future. We bring this up as we plan to package up the theme and place it in the remix repository.

-ItzSwirlz <ubuntucinnamonremix7@gmail.com> - Sat 5:18 EDT Sep 21

**Comment by smurphos** [comment]
Hi,

I maintain the version hosted on Cinnamon Spices and intend to update it to support future Cinnamon versions for as long as is practicable. But why package it when users can just download it via their Themes module?

**Comment by ubuntucinnamon** [comment]
In order for us to put it in the Ubuntu Cinnamon Launchpad Repository, so people can easily install it.

**Comment by brownsr** [comment]
I think the question has been answered, so closing.
