### ISSUE TITLE
Minty, New-Minty: calendar applet (date and time) gets squeezed out to the right when the menu bar is full of window icons

### ISSUE THREAD

**Issue by ShamrockLee** [linuxmint/cinnamon-spices-themes#597]
```
 * Themes version/Build date (to be found in "About.." or in "metadata.json"): ?
 * Cinnamon 4.2.4
 * Debian 11 (bullseye, testing)
 * Intel Corporation UHD Graphics 620 *and* driver used
 * ~/.cinnamon/glass.log not found.
 * Snippet or attachment of ~/.xsession-errors:
[content_of_xsession-errors.txt](https://github.com/linuxmint/cinnamon-spices-themes/files/3827537/content_of_xsession-errors.txt)

 ```

**Notify author of theme**
@brownsr @germanfr 

**Issue**
The date and time shown by the calendar applet gets pushed to the right, overlaps the volume icon and get cut by the edge of the screen when there are many window icons in the panel.

**Steps to reproduce**
1. * In "system settings > Date and Time", check "Use 24h clock", "Display the date", and "Display the time".
    * Or check "Use a custom date format" in "Calendar's right-clicked menu > Config" and input "%A %B %e, %H:%M".
2. Open up 8 or more windows.
**Expected behaviour**
The date and time and the icons in the left starts to be pushed right, causing the date and time to overlap the volume icon and then extended out of the right edge of screen.

Before:
![image](https://user-images.githubusercontent.com/44064051/68532416-e22f2500-0357-11ea-9429-e2911ad489a1.png)

After:
![image](https://user-images.githubusercontent.com/44064051/68532445-27535700-0358-11ea-8387-196b071979af.png)
![image](https://user-images.githubusercontent.com/44064051/68532464-61245d80-0358-11ea-8c61-0470206a5721.png)

**Other information**
It also happens to New-Minty and the BlackMATE option in "System Settings > Themes > Themes > Desktop" (, where "Minty" is also one of the option), but not on other options such as the default "cinnamon".
Minty is one of preinstalled options, while New-Minty was downloaded at "System Settings > Themes > Add/Remove".

**Comment by germanfr** [comment]
I can't reproduce using New-Minty, even with 40 windows open. Could that be a Cinnamon bug?

**Comment by Cpt-Derp** [comment]
@germanfr Happens with the Plata theme. ppa:tista/plata-theme

**Comment by ShamrockLee** [comment]
There are already issues related at the cinnamon repo (the one with a title "Cinnamon Panel Too Wide / Icons Disappear/Overflow `#5042`"), but it's interesting that it only happens to some Desktop theme options.

**Comment by Cpt-Derp** [comment]
@ShamrockLee @germanfr I was able to reproduce with the Minty and New-Minty themes. It's definitely a Cinnamon bug.

![Screenshot from 2019-11-10 13-14-17](https://user-images.githubusercontent.com/3199836/68548570-569baf80-03bc-11ea-91d6-c13f3d105f93.png)
![Screenshot from 2019-11-10 13-12-55](https://user-images.githubusercontent.com/3199836/68548571-569baf80-03bc-11ea-9040-0094e0694108.png)

**Comment by germanfr** [comment]
I couldn't reproduce because I wasn't using the **grouped window list applet**. Now I can reproduce, but **with every theme!** I think this issue belongs to [`linuxmint/cinnamon`](https://github.com/linuxmint/cinnamon).
