### ISSUE TITLE
facebook theme

### ISSUE THREAD

**Issue by dave841** [linuxmint/cinnamon-spices-themes#620]
```facebook theme
  cinnamon 19.3
 * mint linux 19.3
 *rx 580 radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

<!-- Author list: https://github.com/linuxmint/cinnamon-spices-themes/blob/master/.gi thub
linuxmint cinnamon-spices-theme 
**Notify author of theme**
@linuxmint

**Issue**
having a problem with the update on the facebook theme, it has not told me what the error message
does not say what the error message is. it says the cinnamon start up is fin but its one of the applets 
themes on spices theme. am new to this so bear with me  

*

**Comment by brownsr** [comment]
what's the problem you are seeing ?

**Comment by dave841** [comment]
for some reason the error has gone. the problem was the update of the theme, it said the boot up of my cinnamon was fine but the applets, destops, extensions and theme had a problem installing update but it seams to be fine now

**Comment by claudiux** [comment]
@dave841 Try using the SpicesUpdate applet. https://cinnamon-spices.linuxmint.com/applets/view/309

**Comment by dave841** [comment]
its done it. it ok fine thank you so much dont know what went on there update it fine. going to close it now
