### ISSUE TITLE
GTK4 support

### ISSUE THREAD

**Issue by Zipdox** [linuxmint/cinnamon-spices-themes#735]
**Notify author of theme**

Literally everyone. I'm not gonna notify everyone as that's too disruptive.

**Issue**

- GTK4 apps are not themed
- My eyes get hurt by light mode

**Steps to reproduce**

- Install and select any of the themes
- Open gnome-calculator or another gtk4 app

**Expected behaviour**

- App is themed

**Other information**

**Comment by mtwebster** [comment]
Since you provided no real information, I don't know what apps, distro or mint theme versions you're referring to.  This repo is for third-party cinnamon themes, not Gtk.

You probably should report it here:
https://github.com/linuxmint/mint-themes

It seems ok for me in Mint 21/21.1:
![image](https://user-images.githubusercontent.com/262776/208795684-9f556489-fb03-44a5-bb9a-ff667879daa4.png)

**Comment by Zipdox** [comment]
My bad. I'm running Debian sid with Cinnamon. Maybe the apps in Mint aren't using GTK4 yet. None of the themes in this repo have a gtk-4.0 folder so that seems logical to me.

**Comment by mtwebster** [comment]
I'm not sure what themes you're using, but Cinnamon doesn't really have a lot to do with gtk themes - especially the apps like gnome-calculator (a telltale is the fact that both their top and bottom corners are rounded).

I'm not really that familiar with gtk4 but from what I understand they're becoming more difficult (or maybe impossible) to theme - if you're on sid you may have newer versions of gnome-calculator, etc... than I do, and it's simply that they can't be themed any more (they're 'permanently' styled the way gnome wants them to be), though I think there's still a way to have a dark mode.

**Comment by Zipdox** [comment]
stopthemingmy.app isn't inherently against theming at all. They just don't want distros to theme apps by default, as that throws the app developers under the bus if the themes break usability.

![image](https://user-images.githubusercontent.com/42157341/208910542-c3a33cf1-47e8-40ea-9ce9-a37245fbfbe0.png)

I did manage to make it dark mode using `gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'`, but you can see that the window buttons are the Adwaita ones and not the ones of my theme.

**Comment by JosephMcc** [comment]
@mtwebster the issue he is pointing out is that a whole lot of the themes in this repo contain gtk themes along with the Cinnamon themes. And really none of them are up-to-date and support Gtk4.

Adding that support is up to the individual developers of these themes though. Considering that a lot of themes rarely get updated, I'm not sure many of them will get that support.
