### ISSUE TITLE
CBlack: Сontrol panel

### ISSUE THREAD

**Issue by dearsirplease** [linuxmint/cinnamon-spices-themes#737]
Please help me to make the same control panel as in the picture from the site of cinnamon spices
P.S. I recently started using Linux, so I will ask without overly complicated terms and with as detailed explanations as possible

**Comment by fredcw** [comment]
Do you mean the arrangement of the items on the panel or are you asking how to install the CBlack theme?

**Comment by dearsirplease** [comment]
I mean applets, design, menu

**Comment by fredcw** [comment]
You can download and install Cblack theme in the themes dialogue (Menu, search "themes"). But your question should really be asked on mint forums as github is for reporting bugs. Try asking at https://forums.linuxmint.com/viewforum.php?f=211

also [How to change theme - Mint forums](https://forums.linuxmint.com/viewtopic.php?t=284033)
