### ISSUE TITLE
Mint-Y-Yltra-Dark scrollbars not visible

### ISSUE THREAD

**Issue by modomario** [linuxmint/cinnamon-spices-themes#75]
http://imgur.com/a/K7BUu

The scrollbars defined by the theme seem to be working but are either invisible or have the same colour as the backdrop defined by the theme.

**Comment by JosephMcc** [comment]
If you are talking about the scrollbars inside of applications you need to let us know what version of Gtk you are using. I believe these themes are based on Mint-Y so they were built to support gtk3.18. If you are using something else you are likely to run into issues.

**Comment by modomario** [comment]
Hmm sorry I'm using 3.10.8 I'll believe. I'll try & upgrade tomorrow, retry & report back

**Comment by JosephMcc** [comment]
Ok. That would explain the problem. Scrollbar theming changed a lot between 3.10 and 3.18. 3.18 now has the newer overlay type scrollbars.

**Comment by brownsr** [comment]
@modomario Any update ?

**Comment by modomario** [comment]
@brownsr yep, the scrollbar now works. 

There are still some issues with the input fields in some applications lacking hight though. One example being this: http://imgur.com/a/BfCCk in the tabmix plus options (firefox addon). 
I'm not sure what causes it but it's rare enough that it hasn't stopped me from using the theme.

**Comment by brownsr** [comment]
Original issue appears fixed, so closing.
