### ISSUE TITLE
[Sound applet][desktop: Adapta-Nokto]Media control buttons are too close to progress bar.

### ISSUE THREAD

**Issue by imxys** [linuxmint/cinnamon-spices-themes#762]
### Theme version/Build date

"last-edited": 1640073609

### Cinnamon version

5.2.7

### Distribution

Ubuntu 22.04.3

### Graphics hardware *and* driver used

Intel Corporation HD Graphics 530

### Theme name and maintainer

Adapta-Nokto @smurphos

### What happened?

Media control buttons are too close to progress bar.
I want to click pause, but it's too easy to click progress bar and seek music to another position.
I have to move my cursor upper than central position, where the wanted button highlights.
![Peek 2023-12-15 10-56](https://github.com/linuxmint/cinnamon-spices-themes/assets/33591752/4b2a9666-05f8-4c90-a6e9-27465a28791b)
Other desktop theme may not have this problem. Buttons don't overlap on progress bar.
![图片](https://github.com/linuxmint/cinnamon-spices-themes/assets/33591752/2fd39b08-4f37-4d20-9e59-487e70a43ba5)

**Comment by leigh123linux** [comment]
Your cinnamon version is unsupported, reopen if you can reproduce with cinnamon-6.x.x

**Comment by fredcw** [comment]
Affects cinnamon 6 also.
