### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/cinnamon-spices-themes#837]
### Cinnamon version

6.2, 6.4

### Distribution

LMDE 6, Mint 22

### Theme name and maintainer

CBlue @Bundy01

### What happened?

On vertical panels, the grouped-window-list@cinnamon.org looks broken while using CBlue.,

### Other information

![image](https://github.com/user-attachments/assets/e383b717-f00c-4a74-b6f8-00f296f6bda6)

I also have fractional scaling enabled at 125% (if this turns out to be relevant info for this case).

**Comment by Bundy01** [comment]
@anaximeno Thank you very much.
